name: PHP

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/*.php'
      - phpstan.neon.dist
      - .php-cs-fixer.dist.php
      - composer.json
      - composer.lock
      - symfony.lock
      - .github/actions/setup-php/action.yml
      - .github/workflows/php.yml
  push:
    paths:
      - '**/*.php'
      - phpstan.neon.dist
      - .php-cs-fixer.dist.php
      - composer.json
      - composer.lock
      - symfony.lock
      - .github/actions/setup-php/action.yml
      - .github/workflows/php.yml
    branches:
      - trunk

jobs:
  php-cs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-php
      - name: Run PHP-CS-Fixer
        run: composer ecs

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-php
      - name: Generate symfony cache
        run: php bin/console cache:clear
      - name: Run PHPStan
        run: composer phpstan
